import transitfeed


schedule = transitfeed.Schedule()
schedule.AddAgency("Europe Agency", "http://iflyagency.com", "Europe/Madrid", "Europe_Agency")

service_period = schedule.GetDefaultServicePeriod()
service_period.SetStartDate("20070101")
service_period.SetEndDate("20190101")
service_period.SetWeekdayService(True)
service_period.SetDateHasService('20070704', False)

lleida = schedule.AddStop(lng=0.6199348, lat=41.6183423, name="Lleida", stop_id="Lleida")
barcelona = schedule.AddStop(lng=2.0785566, lat=41.3947687, name="Barcelona", stop_id="Barcelona")
paris = schedule.AddStop(lng=2.2071319, lat=48.8587737, name="Paris", stop_id="Paris")
brussels = schedule.AddStop(lng=4.305179, lat=50.854954, name="Brussels", stop_id="Brussels")
amsterdam = schedule.AddStop(lng=4.7581896, lat=52.3745287, name="Amsterdam", stop_id="Amsterdam")
berlin = schedule.AddStop(lng=13.1452858, lat=52.5072095, name="Berlin", stop_id="Berlin")
viena = schedule.AddStop(lng=16.2396348, lat=48.2205994, name="Viena", stop_id="Viena")
praga = schedule.AddStop(lng=14.325199, lat=50.0595849, name="Praga", stop_id="Praga")
milan = schedule.AddStop(lng=9.1075211, lat=45.4627123, name="Milan", stop_id="Milan")
roma = schedule.AddStop(lng=12.395572, lat=41.9099856, name="Roma", stop_id="Roma")
florence = schedule.AddStop(lng=11.1707567, lat=43.7799367, name="Florence", stop_id="Florence")

route_lleida = schedule.AddRoute(short_name="1", long_name="Route Lleida", route_type="Bus", route_id="route_lleida")
route_bcn = schedule.AddRoute(short_name="2", long_name="Route Barcelona", route_type="Bus", route_id="route_bcn")
route_paris = schedule.AddRoute(short_name="3", long_name="Route Paris", route_type="Bus", route_id="route_paris")
route_brussels = schedule.AddRoute(short_name="4", long_name="Route Brusels",route_type="Bus", route_id="route_brussels")
route_amsterdam = schedule.AddRoute(short_name="5", long_name="Route Amsterdam",route_type="Bus", route_id="route_amsterdam")
route_berlin = schedule.AddRoute(short_name="6", long_name="Route Berlin",route_type="Bus", route_id="route_berlin")
route_viena = schedule.AddRoute(short_name="7", long_name="Route Viena",route_type="Bus", route_id="route_viena")
route_praga = schedule.AddRoute(short_name="8", long_name="Route Praga",route_type="Bus", route_id="route_praga")
route_milan = schedule.AddRoute(short_name="9", long_name="Route Milan",route_type="Bus", route_id="route_milan")
route_roma = schedule.AddRoute(short_name="10", long_name="Route Roma",route_type="Bus", route_id="route_roma")
route_florence = schedule.AddRoute(short_name="11", long_name="Route Florence",route_type="Bus", route_id="route_florence")


#From Lleida
triplleidaBcn = route_lleida.AddTrip(schedule, headsign="From Lleida To Barcelona")
triplleidaBcn.AddStopTime(lleida, stop_time='09:00:00')
triplleidaBcn.AddStopTime(barcelona, stop_time='10:30:00')
triplleidaParis = route_lleida.AddTrip(schedule, headsign="From Lleida To Paris")
triplleidaParis.AddStopTime(lleida, stop_time='09:00:00')
triplleidaParis.AddStopTime(paris, stop_time='18:45:00')
triplleidaBrusels = route_lleida.AddTrip(schedule, headsign="From Lleida To Brusels")
triplleidaBrusels.AddStopTime(lleida, stop_time='09:00:00')
triplleidaBrusels.AddStopTime(brussels, stop_time='18:45:00')
triplleidaAms = route_lleida.AddTrip(schedule, headsign="From Lleida To Amsterdam")
triplleidaAms.AddStopTime(lleida, stop_time='09:00:00')
triplleidaAms.AddStopTime(amsterdam, stop_time='18:45:00')
triplleidaBerlin = route_lleida.AddTrip(schedule, headsign="From Lleida To Berlin")
triplleidaBerlin.AddStopTime(lleida, stop_time='09:00:00')
triplleidaBerlin.AddStopTime(berlin, stop_time='18:45:00')
triplleidaViena = route_lleida.AddTrip(schedule, headsign="From Lleida To Viena")
triplleidaViena.AddStopTime(lleida, stop_time='09:00:00')
triplleidaViena.AddStopTime(viena, stop_time='18:45:00')
triplleidaPraga = route_lleida.AddTrip(schedule, headsign="From Lleida To Praga")
triplleidaPraga.AddStopTime(lleida, stop_time='09:00:00')
triplleidaPraga.AddStopTime(praga, stop_time='18:45:00')
triplleidaMilan = route_lleida.AddTrip(schedule, headsign="From Lleida To Milan")
triplleidaMilan.AddStopTime(lleida, stop_time='09:00:00')
triplleidaMilan.AddStopTime(milan, stop_time='18:45:00')
triplleidaRoma = route_lleida.AddTrip(schedule, headsign="From Lleida To Roma")
triplleidaRoma.AddStopTime(lleida, stop_time='09:00:00')
triplleidaRoma.AddStopTime(roma, stop_time='18:45:00')
triplleidaFlorence = route_lleida.AddTrip(schedule, headsign="From Lleida To Florence")
triplleidaFlorence.AddStopTime(lleida, stop_time='09:00:00')
triplleidaFlorence.AddStopTime(florence, stop_time='18:45:00')

#From Barcelona
tripBarcelonaParis = route_bcn.AddTrip(schedule, headsign="From Barcelona To Paris")
tripBarcelonaParis.AddStopTime(barcelona, stop_time='09:00:00')
tripBarcelonaParis.AddStopTime(paris, stop_time='18:45:00')
tripBarcelonaBrussels = route_bcn.AddTrip(schedule, headsign="From Barcelona To Brusels")
tripBarcelonaBrussels.AddStopTime(barcelona, stop_time='09:00:00')
tripBarcelonaBrussels.AddStopTime(brussels, stop_time='18:45:00')
tripBarcelonaAms = route_bcn.AddTrip(schedule, headsign="From Barcelona To Amsterdam")
tripBarcelonaAms.AddStopTime(barcelona, stop_time='09:00:00')
tripBarcelonaAms.AddStopTime(amsterdam, stop_time='18:45:00')
tripBarcelonaBerlin = route_bcn.AddTrip(schedule, headsign="From Barcelona To Berlin")
tripBarcelonaBerlin.AddStopTime(barcelona, stop_time='09:00:00')
tripBarcelonaBerlin.AddStopTime(berlin, stop_time='18:45:00')
tripBarcelonaViena = route_bcn.AddTrip(schedule, headsign="From Barcelona To Viena")
tripBarcelonaViena.AddStopTime(barcelona, stop_time='09:00:00')
tripBarcelonaViena.AddStopTime(viena, stop_time='18:45:00')
tripBarcelonaPraga = route_bcn.AddTrip(schedule, headsign="From Barcelona To Praga")
tripBarcelonaPraga.AddStopTime(barcelona, stop_time='09:00:00')
tripBarcelonaPraga.AddStopTime(praga, stop_time='18:45:00')
tripBarcelonaMilan = route_bcn.AddTrip(schedule, headsign="From Barcelona To Milan")
tripBarcelonaMilan.AddStopTime(barcelona, stop_time='09:00:00')
tripBarcelonaMilan.AddStopTime(milan, stop_time='18:45:00')
tripbarcelonaRoma = route_bcn.AddTrip(schedule, headsign="From Barcelona To Roma")
tripbarcelonaRoma.AddStopTime(barcelona, stop_time='09:00:00')
tripbarcelonaRoma.AddStopTime(roma, stop_time='18:45:00')
tripbarcelonaFlorence = route_bcn.AddTrip(schedule, headsign="From Barcelona To Florence")
tripbarcelonaFlorence.AddStopTime(barcelona, stop_time='09:00:00')
tripbarcelonaFlorence.AddStopTime(florence, stop_time='18:45:00')

#From Paris
tripParis1 = route_paris.AddTrip(schedule, headsign="From Paris To Brusels")
tripParis1.AddStopTime(paris, stop_time='09:00:00')
tripParis1.AddStopTime(brussels, stop_time='18:45:00')
tripParis2 = route_paris.AddTrip(schedule, headsign="From Paris To Amsterdam")
tripParis2.AddStopTime(paris, stop_time='09:00:00')
tripParis2.AddStopTime(amsterdam, stop_time='18:45:00')
tripParis3 = route_paris.AddTrip(schedule, headsign="From Paris To Berlin")
tripParis3.AddStopTime(paris, stop_time='09:00:00')
tripParis3.AddStopTime(berlin, stop_time='18:45:00')
tripParis4 = route_paris.AddTrip(schedule, headsign="From Paris To Viena")
tripParis4.AddStopTime(paris, stop_time='09:00:00')
tripParis4.AddStopTime(viena, stop_time='18:45:00')
tripParis5 = route_paris.AddTrip(schedule, headsign="From Paris To Praga")
tripParis5.AddStopTime(paris, stop_time='09:00:00')
tripParis5.AddStopTime(praga, stop_time='18:45:00')
tripParis6 = route_paris.AddTrip(schedule, headsign="From Paris To Milan")
tripParis6.AddStopTime(paris, stop_time='09:00:00')
tripParis6.AddStopTime(milan, stop_time='18:45:00')
tripParis7 = route_paris.AddTrip(schedule, headsign="From Paris To Roma")
tripParis7.AddStopTime(paris, stop_time='09:00:00')
tripParis7.AddStopTime(roma, stop_time='18:45:00')
tripParis8 = route_paris.AddTrip(schedule, headsign="From Paris To Florence")
tripParis8.AddStopTime(paris, stop_time='09:00:00')
tripParis8.AddStopTime(florence, stop_time='18:45:00')

#From Brusels
tripBrussels1 = route_brussels.AddTrip(schedule, headsign="From Brusels To Amsterdam")
tripBrussels1.AddStopTime(brussels, stop_time='09:00:00')
tripBrussels1.AddStopTime(amsterdam, stop_time='18:45:00')
tripBrussels2 = route_brussels.AddTrip(schedule, headsign="From Brusels To Berlin")
tripBrussels2.AddStopTime(brussels, stop_time='09:00:00')
tripBrussels2.AddStopTime(berlin, stop_time='18:45:00')
tripBrussels3 = route_brussels.AddTrip(schedule, headsign="From Brusels To Viena")
tripBrussels3.AddStopTime(brussels, stop_time='09:00:00')
tripBrussels3.AddStopTime(viena, stop_time='18:45:00')
tripBrussels4 = route_brussels.AddTrip(schedule, headsign="From Brusels To Praga")
tripBrussels4.AddStopTime(brussels, stop_time='09:00:00')
tripBrussels4.AddStopTime(praga, stop_time='18:45:00')
tripBrussels4 = route_brussels.AddTrip(schedule, headsign="From Brusels To Milan")
tripBrussels4.AddStopTime(brussels, stop_time='09:00:00')
tripBrussels4.AddStopTime(milan, stop_time='18:45:00')
tripBrussel5 = route_brussels.AddTrip(schedule, headsign="From Brusels To Roma")
tripBrussel5.AddStopTime(brussels, stop_time='09:00:00')
tripBrussel5.AddStopTime(roma, stop_time='18:45:00')
tripBrussel6 = route_brussels.AddTrip(schedule, headsign="From Brusels To Florence")
tripBrussel6.AddStopTime(brussels, stop_time='09:00:00')
tripBrussel6.AddStopTime(florence, stop_time='18:45:00')

#From Amsterdam
tripAmsterdam1 = route_amsterdam.AddTrip(schedule, headsign="From Amsterdam To Berlin")
tripAmsterdam1.AddStopTime(amsterdam, stop_time='09:00:00')
tripAmsterdam1.AddStopTime(berlin, stop_time='18:45:00')
tripAmsterdam2 = route_amsterdam.AddTrip(schedule, headsign="From Amsterdam To Viena")
tripAmsterdam2.AddStopTime(amsterdam, stop_time='09:00:00')
tripAmsterdam2.AddStopTime(viena, stop_time='18:45:00')
tripAmsterdam3 = route_amsterdam.AddTrip(schedule, headsign="From Amsterdam To Praga")
tripAmsterdam3.AddStopTime(amsterdam, stop_time='09:00:00')
tripAmsterdam3.AddStopTime(praga, stop_time='18:45:00')
tripAmsterdam4 = route_amsterdam.AddTrip(schedule, headsign="From Amsterdam To Milan")
tripAmsterdam4.AddStopTime(amsterdam, stop_time='09:00:00')
tripAmsterdam4.AddStopTime(milan, stop_time='18:45:00')
tripAmsterdam5 = route_amsterdam.AddTrip(schedule, headsign="From Amsterdam To Roma")
tripAmsterdam5.AddStopTime(amsterdam, stop_time='09:00:00')
tripAmsterdam5.AddStopTime(roma, stop_time='18:45:00')
tripAmsterdam6 = route_amsterdam.AddTrip(schedule, headsign="From Amsterdam To Florence")
tripAmsterdam6.AddStopTime(amsterdam, stop_time='09:00:00')
tripAmsterdam6.AddStopTime(florence, stop_time='18:45:00')

#From Berlin
tripBerlinViena = route_berlin.AddTrip(schedule, headsign="From Berlin To Viena")
tripBerlinViena.AddStopTime(berlin, stop_time='09:00:00')
tripBerlinViena.AddStopTime(viena, stop_time='18:45:00')
tripBerlinPraga = route_berlin.AddTrip(schedule, headsign="From Berlin To Praga")
tripBerlinPraga.AddStopTime(berlin, stop_time='09:00:00')
tripBerlinPraga.AddStopTime(praga, stop_time='18:45:00')
tripBerlinMilan = route_berlin.AddTrip(schedule, headsign="From Berlin To Milan")
tripBerlinMilan.AddStopTime(berlin, stop_time='09:00:00')
tripBerlinMilan.AddStopTime(milan, stop_time='18:45:00')
tripBerlinRoma = route_berlin.AddTrip(schedule, headsign="From Berlin To Roma")
tripBerlinRoma.AddStopTime(berlin, stop_time='09:00:00')
tripBerlinRoma.AddStopTime(roma, stop_time='18:45:00')
tripberlinFlorence = route_berlin.AddTrip(schedule, headsign="From Berlin To Florence")
tripberlinFlorence.AddStopTime(berlin, stop_time='09:00:00')
tripberlinFlorence.AddStopTime(florence, stop_time='18:45:00')

#From Viena
tripVienaPraga = route_viena.AddTrip(schedule, headsign="From Viena To Praga")
tripVienaPraga.AddStopTime(viena, stop_time='09:00:00')
tripVienaPraga.AddStopTime(praga, stop_time='18:45:00')
tripVienaMilan = route_viena.AddTrip(schedule, headsign="From Viena To Milan")
tripVienaMilan.AddStopTime(viena, stop_time='09:00:00')
tripVienaMilan.AddStopTime(milan, stop_time='18:45:00')
tripVienaRoma = route_viena.AddTrip(schedule, headsign="From Viena To Roma")
tripVienaRoma.AddStopTime(viena, stop_time='09:00:00')
tripVienaRoma.AddStopTime(roma, stop_time='18:45:00')
tripVienaFlorencia = route_viena.AddTrip(schedule, headsign="From Viena To Florence")
tripVienaFlorencia.AddStopTime(viena, stop_time='09:00:00')
tripVienaFlorencia.AddStopTime(florence, stop_time='18:45:00')

#From Praga
tripPragaMilan = route_praga.AddTrip(schedule, headsign="From Praga To Milan")
tripPragaMilan.AddStopTime(praga, stop_time='09:00:00')
tripPragaMilan.AddStopTime(milan, stop_time='18:45:00')
tripPragaRoma = route_praga.AddTrip(schedule, headsign="From Praga To Roma")
tripPragaRoma.AddStopTime(praga, stop_time='09:00:00')
tripPragaRoma.AddStopTime(roma, stop_time='18:45:00')
tripPragaFlorence = route_praga.AddTrip(schedule, headsign="From Praga To Florence")
tripPragaFlorence.AddStopTime(praga, stop_time='09:00:00')
tripPragaFlorence.AddStopTime(florence, stop_time='18:45:00')

#From Milan
tripMilanRoma = route_milan.AddTrip(schedule, headsign="From Milan To Roma")
tripMilanRoma.AddStopTime(milan, stop_time='09:00:00')
tripMilanRoma.AddStopTime(roma, stop_time='18:45:00')
tripMilanFlorence = route_milan.AddTrip(schedule, headsign="From Milan To Florence")
tripMilanFlorence.AddStopTime(milan, stop_time='09:00:00')
tripMilanFlorence.AddStopTime(florence, stop_time='18:45:00')

#From Roma
tripRomaFlorence = route_roma.AddTrip(schedule, headsign="From Roma To Florence")
tripRomaFlorence.AddStopTime(roma, stop_time='09:00:00')
tripRomaFlorence.AddStopTime(florence, stop_time='18:45:00')




schedule.Validate()
schedule.WriteGoogleTransitFeed('google_transit_europe.zip')