# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floybd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('valid_date', models.DateField()),
                ('key', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['name', 'province']},
        ),
    ]
