# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floybd', '0002_auto_20170522_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='valid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
