# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floybd', '0003_auto_20170522_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(blank=True, max_length=200, null=True)),
                ('agency_url', models.URLField()),
                ('agency_name', models.CharField(max_length=200)),
                ('agency_timezone', models.CharField(max_length=5)),
                ('agency_lang', models.CharField(blank=True, max_length=2, null=True)),
                ('agency_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('agency_fare_url', models.URLField(blank=True, null=True)),
                ('agency_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('route_short_name', models.CharField(max_length=200)),
                ('route_long_name', models.CharField(max_length=200)),
                ('route_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('route_type', models.IntegerField(choices=[(0, 'Tram, Streetcar, Light rail'), (1, 'Subway, Metro'), (2, 'Rail'), (3, 'Bus'), (4, 'Ferry'), (5, 'Cable Car'), (6, 'Gondola, Suspended cable car'), (7, 'Funicular')], default=0)),
                ('route_url', models.URLField(blank=True, null=True)),
                ('route_color', models.CharField(blank=True, max_length=6, null=True)),
                ('route_text_color', models.CharField(blank=True, max_length=6, null=True)),
                ('agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='floybd.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('stop_code', models.CharField(blank=True, max_length=200, null=True)),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('zone_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stop_url', models.URLField(blank=True, null=True)),
                ('location_type', models.IntegerField(blank=True, choices=[(0, 'Stop'), (1, 'Station')])),
                ('stop_timezone', models.CharField(blank=True, max_length=200, null=True)),
                ('wheelchair_boarding', models.IntegerField(blank=True, choices=[(0, 'No Information'), (1, 'At least one place'), (2, 'No Place')])),
            ],
        ),
        migrations.CreateModel(
            name='Stop_times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('stop_sequence', models.PositiveIntegerField()),
                ('stop_headsign', models.CharField(max_length=200)),
                ('pickup_type', models.IntegerField(blank=True, choices=[(0, 'Regularly scheduled pickup'), (1, 'No pickup available'), (2, 'Must phone agency to arrange pickup'), (3, 'Must coordinate with driver to arrange pickup')], default=0, null=True)),
                ('drop_off_type', models.IntegerField(blank=True, choices=[(0, 'Regularly scheduled drop off'), (1, 'No drop off available'), (2, 'Must phone agency to arrange drop off'), (3, 'Must coordinate with driver to arrange drop off')], default=0, null=True)),
                ('timepoint', models.IntegerField(choices=[(0, 'Times are considered approximate'), (1, 'Times are considered exact')])),
                ('stop_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='floybd.Stop')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('trip_headsign', models.CharField(blank=True, max_length=200, null=True)),
                ('trip_short_name', models.CharField(blank=True, max_length=200, null=True)),
                ('direction_id', models.IntegerField(blank=True, choices=[(0, 'Outbound'), (1, 'Inbound')], null=True)),
                ('block_id', models.CharField(max_length=200)),
                ('wheelchair_accessible', models.IntegerField(choices=[(0, 'No Information'), (1, 'At least one place'), (2, 'No Place')], default=0)),
                ('bikes_allowed', models.IntegerField(choices=[(0, 'No Information'), (1, 'At least one place'), (2, 'No Place')], default=0)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='floybd.Route')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='floybd.Calendar')),
            ],
        ),
        migrations.AddField(
            model_name='stop_times',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='floybd.Trip'),
        ),
    ]
