# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floybd', '0004_auto_20170605_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop_times',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='stop_times',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
