# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floybd', '0006_auto_20170605_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar_dates',
            fields=[
                ('service_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('exception_type', models.IntegerField(choices=[(1, 'Added'), (2, 'Removed')])),
            ],
        ),
        migrations.CreateModel(
            name='Fare_Attributes',
            fields=[
                ('fare_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField()),
                ('currency_type', models.CharField(max_length=3)),
                ('payment_method', models.IntegerField(choices=[(0, 'On Board'), (1, 'Before Boarding')])),
                ('transfers', models.IntegerField(blank=True, choices=[(0, 'No transfers permitted'), (1, 'Passenger may transfer once'), (2, 'Passenger may transfer twice')], null=True)),
                ('transfer_duration', models.FloatField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stop',
            name='location_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Stop'), (1, 'Station')], null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='wheelchair_boarding',
            field=models.IntegerField(blank=True, choices=[(0, 'No Information'), (1, 'At least one place'), (2, 'No Place')], null=True),
        ),
    ]
