# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floybd', '0007_auto_20170605_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
