# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floybd', '0008_auto_20170605_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop_times',
            name='timepoint',
            field=models.IntegerField(blank=True, choices=[(0, 'Times are considered approximate'), (1, 'Times are considered exact')], null=True),
        ),
    ]
