# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floybd', '0009_auto_20170605_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop_times',
            name='stop_headsign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stop_times',
            name='stop_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
