# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floybd', '0010_auto_20170605_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar_dates',
            new_name='Calendar_date',
        ),
        migrations.RenameModel(
            old_name='Fare_Attributes',
            new_name='Fare_Attribute',
        ),
        migrations.RenameModel(
            old_name='Stop_times',
            new_name='Stop_time',
        ),
    ]
