# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floybd', '0011_auto_20170605_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='id',
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_id',
            field=models.CharField(default=1, max_length=200, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='agency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='floybd.Agency'),
        ),
        migrations.AlterField(
            model_name='stop_time',
            name='stop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floybd.Stop'),
        ),
        migrations.AlterField(
            model_name='stop_time',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floybd.Trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floybd.Route'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floybd.Calendar'),
        ),
    ]
